import type { KnowledgeSection, Language, LangDict } from "./types";

// ──────────────────────────────────────────────
// KNOWLEDGE BASE
// ──────────────────────────────────────────────

export const KNOWLEDGE_BASE: KnowledgeSection[] = [
  // ── NELFUND SECTIONS ──
  {
    id: "NELFUND-A",
    source: "NELFUND",
    section: "A",
    title: "What is NELFUND?",
    content:
      "The Nigerian Education Loan Fund (NELFUND) is a Federal Government initiative that provides interest-free loans to Nigerian students in tertiary institutions. It covers tuition fees and upkeep. The application is completely free — no agent fees, no processing charges.",
    url: "https://portal.nelf.gov.ng",
  },
  {
    id: "NELFUND-B",
    source: "NELFUND",
    section: "B",
    title: "Eligibility Requirements",
    content:
      "To apply for a NELFUND loan, you must: (1) Be a Nigerian citizen. (2) Be enrolled in a Federal or State tertiary institution (University, Polytechnic, or College of Education). (3) Provide your JAMB/Matriculation number, NIN, and Bank Verification Number (BVN). (4) Have a valid student ID. (5) Not have any outstanding loans from previous applications.",
    url: "https://portal.nelf.gov.ng",
  },
  {
    id: "NELFUND-C",
    source: "NELFUND",
    section: "C",
    title: "Loan Types: Tuition & Upkeep",
    content:
      "NELFUND offers two loan types: (1) Tuition Loan — paid directly to your institution. (2) Upkeep Loan — paid monthly to your personal bank account for living expenses. You can apply for one or both. The loan is interest-free, and repayment begins two years after completing your National Youth Service Corps (NYSC) program.",
    url: "https://portal.nelf.gov.ng",
  },
  {
    id: "NELFUND-D",
    source: "NELFUND",
    section: "D",
    title: "Application Process (Step-by-Step)",
    content:
      "Step 1: Visit portal.nelf.gov.ng. Step 2: Click 'Apply Now' and create an account using your email and phone number. Step 3: Verify your email and phone via OTP. Step 4: Log in and complete your profile — upload your NIN, BVN, student ID, and JAMB number. Step 5: Select your institution and course of study. Step 6: Choose loan type (Tuition, Upkeep, or Both). Step 7: Review and submit. Step 8: Track your application status on the dashboard. Processing takes 2-4 weeks.",
    url: "https://portal.nelf.gov.ng",
  },
  {
    id: "NELFUND-E",
    source: "NELFUND",
    section: "E",
    title: "Required Documents Checklist",
    content:
      "You need the following documents: (1) Valid National Identification Number (NIN). (2) Bank Verification Number (BVN). (3) JAMB/Matriculation number. (4) Admission letter from your institution. (5) Student ID card. (6) Passport photograph (recent). (7) Bank account details (for upkeep loan disbursement). All documents must be clear and legible — blurry or expired documents will be rejected.",
    url: "https://portal.nelf.gov.ng",
  },
  {
    id: "NELFUND-F",
    source: "NELFUND",
    section: "F",
    title: "Repayment Terms",
    content:
      "Repayment starts 2 years after completing NYSC. You repay in installments deducted directly from your salary by your employer (if employed) or through voluntary payment. The loan is interest-free — you only repay the exact amount you received. Late payment attracts a penalty of 1% of the outstanding balance per month. You can also repay early without any penalty.",
    url: "https://portal.nelf.gov.ng",
  },
  {
    id: "NELFUND-G",
    source: "NELFUND",
    section: "G",
    title: "Scam Alert: Official NELFUND Process is FREE",
    content:
      "WARNING: NELFUND application is 100% FREE. There are NO agents, NO processing fees, and NO middlemen. Do NOT pay anyone who claims they can help you apply for a fee. Official channels: portal.nelf.gov.ng. If you encounter anyone asking for money to process your NELFUND application, report them immediately to NELFUND support or the nearest police station.",
    url: "https://portal.nelf.gov.ng",
  },

  // ── CAC SECTIONS ──
  {
    id: "CAC-A",
    source: "CAC",
    section: "A",
    title: "What is CAC Business Registration?",
    content:
      "The Corporate Affairs Commission (CAC) is the Nigerian government agency that registers and regulates all business names, incorporated trustees, and companies in Nigeria. Registering your business with CAC makes it a legal entity, protects your business name, and allows you to open a corporate bank account. The most common registration types are: Business Name (for sole traders/small businesses), Limited Liability Company (for larger businesses), and Incorporated Trustees (for NGOs).",
    url: "https://pre.cac.gov.ng",
  },
  {
    id: "CAC-B",
    source: "CAC",
    section: "B",
    title: "Business Name Registration Process",
    content:
      "Step 1: Go to pre.cac.gov.ng and create an account. Step 2: Log in and click 'New Registration'. Step 3: Select 'Business Name' as registration type. Step 4: Search for your proposed business name to check availability. Step 5: Fill in your business details (address, nature of business). Step 6: Upload required documents. Step 7: Pay the registration fee (N10,000 - N15,000 for Business Name via Remita). Step 8: Submit and wait for approval (usually 1-3 working days). Step 9: Download your Certificate of Registration.",
    url: "https://pre.cac.gov.ng",
  },
  {
    id: "CAC-C",
    source: "CAC",
    section: "C",
    title: "Required Documents for CAC Registration",
    content:
      "For Business Name: (1) Valid means of ID (NIN, International Passport, or Driver's License). (2) Passport photograph. (3) Proof of business address (utility bill or tenancy agreement). (4) NIN verification slip. For Limited Liability Company: (1) All the above for each director. (2) Memorandum and Articles of Association (MEMART). (3) Registered address. (4) Director/shareholder details. (5) CAC 1.1 and CAC 2 forms.",
    url: "https://pre.cac.gov.ng",
  },
  {
    id: "CAC-D",
    source: "CAC",
    section: "D",
    title: "Fees and Processing Times",
    content:
      "Business Name Registration: N10,000 - N15,000 (processing 1-3 days). Limited Liability Company: N50,000 - N100,000 depending on share capital (processing 2-5 days). Incorporated Trustees: N20,000 - N30,000 (processing 5-10 days). Express registration (same day) is available at double the fee. All payments are made via Remita on the official CAC portal only. Do not pay anyone off-platform.",
    url: "https://pre.cac.gov.ng",
  },
  {
    id: "CAC-E",
    source: "CAC",
    section: "E",
    title: "Post-Registration: What You Get",
    content:
      "After successful registration, you receive: (1) Certificate of Registration (digital PDF). (2) Business Name search receipt. (3) Access to your CAC dashboard. With these, you can: Open a corporate bank account, Register for taxes with FIRS, Apply for business permits, Enter into contracts, and Protect your business name legally. Your registration is valid for life unless you voluntarily dissolve the business.",
    url: "https://pre.cac.gov.ng",
  },
  {
    id: "CAC-F",
    source: "CAC",
    section: "F",
    title: "Scam Alert: CAC Registration Scams",
    content:
      "WARNING: CAC registration fees are fixed and published on the official portal (pre.cac.gov.ng). Do NOT pay more than the official fee. Beware of agents who claim they have 'connections' inside CAC to speed up your registration. The CAC portal is self-service — you can do everything yourself. Only use pre.cac.gov.ng. Never pay via personal bank accounts or mobile money — only pay via Remita on the portal.",
    url: "https://pre.cac.gov.ng",
  },
];

// ──────────────────────────────────────────────
// MULTILINGUAL STRINGS
// ──────────────────────────────────────────────

export const LANG_STRINGS: LangDict = {
  en: {
    placeholder: "Type your message...",
    send: "Send",
    newChat: "New Chat",
    myApps: "My Applications",
    chat: "Chat",
    noApps: "No applications yet",
    noAppsDesc: "Ask me about NELFUND or CAC registration and I will create a checklist for you.",
    appProgress: "Progress",
    documents: "Documents Needed",
    officialCost: "Official Cost",
    processingTime: "Processing Time",
    portalLink: "Go to Official Portal",
    printChecklist: "Print",
    downloadChecklist: "Download",
    scamTitle: "SCAM ALERT",
    scamBody: "The official process is FREE. Do not pay anyone claiming to help you apply.",
    kbSource: "Source",
    section: "Section",
    todo: "To Do",
    inProgress: "In Progress",
    completed: "Completed",
    typeMessage: "Type your message...",
    promptLoan: "I want to apply for a NELFUND student loan",
    promptCAC: "I want to register my business with CAC",
    promptHow: "How does NELFUND repayment work?",
    promptCost: "How much is CAC registration?",
    hello: "Hello!",
    welcome: "Welcome to Citizen AI",
    welcomeDesc: "I can help you navigate NELFUND student loans and CAC business registration. Ask me anything in English, Pidgin, Hausa, Yoruba, or Igbo.",
    selectOption: "Select an option below to get started, or type your question.",
    nelfund: "NELFUND Loan",
    cac: "CAC Registration",
    settings: "Settings",
    about: "About Citizen AI",
    darkMode: "Dark",
    lightMode: "Light",
    thread: "Chat",
    threads: "Chats",
    delete: "Delete",
    confirm: "Confirm",
    cancel: "Cancel",
    yes: "Yes",
    no: "No",
    loading: "Loading...",
    error: "Something went wrong.",
    retry: "Retry",
    close: "Close",
    back: "Back",
    next: "Next",
    finish: "Finish",
    save: "Save",
    share: "Share",
    copy: "Copy",
    copied: "Copied!",
    print: "Print",
    download: "Download",
    status: "Status",
    notCovered: "This information is not covered in our knowledge base. Please visit the official portal for more details.",
    official: "Official Portal",
    free: "Free",
    warning: "Warning",
    info: "Info",
    tip: "Tip",
  },
  pidgin: {
    placeholder: "Type your message...",
    send: "Send",
    newChat: "New Chat",
    myApps: "My Applications",
    chat: "Chat",
    noApps: "You no get any application yet",
    noAppsDesc: "Ask me about NELFUND or CAC registration, I go create checklist for you.",
    appProgress: "Progress",
    documents: "Documents Wey You Need",
    officialCost: "Official Cost",
    processingTime: "How Long E Take",
    portalLink: "Go to Official Portal",
    printChecklist: "Print",
    downloadChecklist: "Download",
    scamTitle: "SCAM ALERT!",
    scamBody: "The official process na FREE. No pay anybody wey talk say e go help you apply.",
    kbSource: "Source",
    section: "Section",
    todo: "To Do",
    inProgress: "In Progress",
    completed: "Done",
    typeMessage: "Type your message...",
    promptLoan: "I wan apply for NELFUND student loan",
    promptCAC: "I wan register my business for CAC",
    promptHow: "How NELFUND repayment take work?",
    promptCost: "How much CAC registration?",
    hello: "How far!",
    welcome: "Welcome to Citizen AI",
    welcomeDesc: "I fit help you with NELFUND student loan and CAC business registration. Ask me anything for English, Pidgin, Hausa, Yoruba, or Igbo.",
    selectOption: "Choose one option below to start, or type your question.",
    nelfund: "NELFUND Loan",
    cac: "CAC Registration",
    settings: "Settings",
    about: "About Citizen AI",
    darkMode: "Dark",
    lightMode: "Light",
    thread: "Chat",
    threads: "Chats",
    delete: "Delete",
    confirm: "Confirm",
    cancel: "Cancel",
    yes: "Yes",
    no: "No",
    loading: "Dey load...",
    error: "Something dey wrong.",
    retry: "Try again",
    close: "Close",
    back: "Back",
    next: "Next",
    finish: "Finish",
    save: "Save",
    share: "Share",
    copy: "Copy",
    copied: "Don Copy!",
    print: "Print",
    download: "Download",
    status: "Status",
    notCovered: "Dis info no dey our knowledge base. Check official portal for more details.",
    official: "Official Portal",
    free: "Free",
    warning: "Warning",
    info: "Info",
    tip: "Tip",
  },
  ha: {
    placeholder: "Rubuta sakonka...",
    send: "Aika",
    newChat: "Sabuwar Hira",
    myApps: "Aikace-aikacena",
    chat: "Hira",
    noApps: "Baka da wani aikace-aikace ba tukuna",
    noAppsDesc: "Tambaye ni game da NELFUND ko CAC rajista, zan kirkirar maka jerin ayyuka.",
    appProgress: "Ci gaba",
    documents: "Takardun da ake Bukata",
    officialCost: "Kudin Hukuma",
    processingTime: "Lokacin Aiki",
    portalLink: "Je zuwa Portal na Hukuma",
    printChecklist: "Buga",
    downloadChecklist: "Sauke",
    scamTitle: "GARGADIN ZAMBA!",
    scamBody: "Tsarin hukuma kyauta ne. Kada ka biya wani wanda yace zai taimaka maka kayi nema.",
    kbSource: "Madogara",
    section: "Sashe",
    todo: "Yi",
    inProgress: "Ana Ci Gaba",
    completed: "An Kammala",
    typeMessage: "Rubuta sakonka...",
    promptLoan: "Ina son neman lamunin dalibi na NELFUND",
    promptCAC: "Ina son yin rijistar kasuwanci na a CAC",
    promptHow: "Yaya biyan NELFUND take aiki?",
    promptCost: "Nawa ne kudin rijistar CAC?",
    hello: "Sannu!",
    welcome: "Barka da zuwa Citizen AI",
    welcomeDesc: "Zan taimaka maka wajen samun lamunin dalibi na NELFUND da rijistar kasuwanci na CAC. Tambaye ni komai da Turanci, Pidgin, Hausa, Yoruba, ko Igbo.",
    selectOption: "Zabi wani zaɓi a ƙasa don farawa, ko rubuta tambayarka.",
    nelfund: "Lamunin NELFUND",
    cac: "Rijistar CAC",
    settings: "Saituna",
    about: "Game da Citizen AI",
    darkMode: "Duhu",
    lightMode: "Haskke",
    thread: "Hira",
    threads: "Hirori",
    delete: "Share",
    confirm: "Tabbatar",
    cancel: "Soke",
    yes: "E",
    no: "A'a",
    loading: "Ana lodawa...",
    error: "Wani abu yayi kuskure.",
    retry: "Sake gwadawa",
    close: "Rufe",
    back: "Geri",
    next: "Gaba",
    finish: "Gama",
    save: "Ajiye",
    share: "Raba",
    copy: "Kwafi",
    copied: "An kwafi!",
    print: "Buga",
    download: "Sauke",
    status: "Matsayi",
    notCovered: "Wannan bayanin baya cikin tarihinmu. Ziyarci portal na hukuma don karin bayani.",
    official: "Portal na Hukuma",
    free: "Kyauta",
    warning: "Gargadi",
    info: "Bayani",
    tip: "Shawara",
  },
  yo: {
    placeholder: "Tẹ ifiranṣẹ rẹ...",
    send: "Firanṣẹ",
    newChat: "Ìbẹ̀rẹ̀ Ìbánisọ̀rọ̀ Tuntun",
    myApps: "Awọn Ohun elo Mi",
    chat: "Ìbánisọ̀rọ̀",
    noApps: "Ko tii si awọn ohun elo rẹ",
    noAppsDesc: "Beere lọwọ mi nipa NELFUND tabi iforukọsilẹ CAC, emi yoo ṣẹda atokọ iṣẹ-ṣiṣe fun ọ.",
    appProgress: "Ilọsiwaju",
    documents: "Awọn Iwe ti o nilo",
    officialCost: "Iye owo ti ijọba",
    processingTime: "Akoko Ṣiṣe",
    portalLink: "Lọ si Portal Ijọba",
    printChecklist: "Tẹ̀jade",
    downloadChecklist: "Gba lati ayelujara",
    scamTitle: "IKILO JINN!",
    scamBody: "Ilana ijọba jẹ ọfẹ. Maṣe san owo fun ẹnikẹni ti o sọ pe yoo ran ọ lọwọ lati beere.",
    kbSource: "Orisun",
    section: "Apa",
    todo: "Ṣe",
    inProgress: "Ni Ilọsiwaju",
    completed: "Ti Pari",
    typeMessage: "Tẹ ifiranṣẹ rẹ...",
    promptLoan: "Mo fẹ́ béèrè fún àwínni akẹ́kọ̀ọ́ NELFUND",
    promptCAC: "Mo fẹ́ forúkọṣilẹ̀ iṣẹ́ mi ní CAC",
    promptHow: "Báwo ni sísanwó NELFUND ṣe ń ṣiṣẹ́?",
    promptCost: "Elo ni iforukọsilẹ CAC?",
    hello: "Pẹlẹ o!",
    welcome: "Kaabo si Citizen AI",
    welcomeDesc: "Mo le ran ọ lọwọ lati wa awin akeko NELFUND ati iforukọsilẹ iṣowo CAC. Beere lọwọ mi ni Gẹ̀ẹ́sì, Pidgin, Hausa, Yoruba, tabi Igbo.",
    selectOption: "Yan aṣayan kan ni isalẹ lati bẹrẹ, tabi tẹ ibeere rẹ.",
    nelfund: "Awin NELFUND",
    cac: "Iforukọsilẹ CAC",
    settings: "Àwọn ètò",
    about: "Nipa Citizen AI",
    darkMode: "Dudu",
    lightMode: "Imọlẹ",
    thread: "Ìbánisọ̀rọ̀",
    threads: "Awọn ìbánisọ̀rọ̀",
    delete: "Pa rẹ",
    confirm: "Jẹrisi",
    cancel: "Fagilee",
    yes: "Bẹẹni",
    no: "Rara",
    loading: "N gbera...",
    error: "Ohun kan ti aṣiṣe.",
    retry: "Tun gbiyanju",
    close: "Pa",
    back: "Pada",
    next: "Atẹle",
    finish: "Pari",
    save: "Fipamọ",
    share: "Pin",
    copy: "Daakọ",
    copied: "Ti daakọ!",
    print: "Tẹ̀jade",
    download: "Gba lati ayelujara",
    status: "Ipo",
    notCovered: "Alaye yii ko si ninu ile-ikawe wa. Jọwọ ṣabẹwo si portal ijọba fun alaye diẹ sii.",
    official: "Portal Ijọba",
    free: "Ọfẹ",
    warning: "Ikilọ",
    info: "Alaye",
    tip: "Imọran",
  },
  ig: {
    placeholder: "Dee ozi gị...",
    send: "Ziga",
    newChat: "Mkparịta Ọhụrụ",
    myApps: "Ngwa M",
    chat: "Mkparịta ụka",
    noApps: "Ị nwebeghị ngwa ọ bụla",
    noAppsDesc: "Jụọ m maka NELFUND ma ọ bụ ndebanye CAC, a ga m emepụta ndepụta ọrụ maka gị.",
    appProgress: "Ọganihu",
    documents: "Akwụkwọ Ndị Dị Mkpa",
    officialCost: "Ọnụ ego Gọọmentị",
    processingTime: "Oge Nhazi",
    portalLink: "Gaa na Portal Gọọmentị",
    printChecklist: "Bipụta",
    downloadChecklist: "Budata",
    scamTitle: "ỊDỌ AKA NA NTỊ!",
    scamBody: "Usoro gọọmentị bụ n'efu. Akwụla onye ọ bụla na-ekwu na ọ ga-enyere gị aka ịtinye akwụkwọ.",
    kbSource: "Isi mmalite",
    section: "Ngalaba",
    todo: "Mee",
    inProgress: "Ọ na-aga n'ihu",
    completed: "Emechara",
    typeMessage: "Dee ozi gị...",
    promptLoan: "Achọrọ m ịtinye akwụkwọ maka mbinye ego ụmụ akwụkwọ NELFUND",
    promptCAC: "Achọrọ m ịdebanye aha azụmahịa m na CAC",
    promptHow: "Olee otú ịkwụghachi NELFUND si arụ ọrụ?",
    promptCost: "Ego ole bụ ndebanye CAC?",
    hello: "Ndewo!",
    welcome: "Nnọọ na Citizen AI",
    welcomeDesc: "Enwere m ike inyere gị aka ịhụ mbinye ego ụmụ akwụkwọ NELFUND na ndebanye aha azụmahịa CAC. Jụọ m ihe ọ bụla n'asụsụ Bekee, Pidgin, Hausa, Yoruba, ma ọ bụ Igbo.",
    selectOption: "Họrọ otu nhọrọ n'okpuru iji bido, ma ọ bụ dee ajụjụ gị.",
    nelfund: "Mbinye NELFUND",
    cac: "Ndebanye CAC",
    settings: "Ntọala",
    about: "Gbasara Citizen AI",
    darkMode: "Ọchịchịrị",
    lightMode: "Ìhè",
    thread: "Mkparịta ụka",
    threads: "Mkparịta ụka",
    delete: "Hichapụ",
    confirm: "Kwenye",
    cancel: "Kagbuo",
    yes: "Ee",
    no: "Mba",
    loading: "Na-ebunye...",
    error: "Ihe mejọrọ.",
    retry: "Nwaa ọzọ",
    close: "Mechie",
    back: "Laghachi",
    next: "Ọzọ",
    finish: "Mechie",
    save: "Chekwa",
    share: "Kesaa",
    copy: "Detuo",
    copied: "Edetuola!",
    print: "Bipụta",
    download: "Budata",
    status: "Ọnọdụ",
    notCovered: "Ozi a adịghị n'ọbá akwụkwọ anyị. Biko gaa na portal gọọmentị maka nkọwa zuru ezu.",
    official: "Portal Gọọmentị",
    free: "N'efu",
    warning: "Ịdọ aka na ntị",
    info: "Ozi",
    tip: "Nduzi",
  },
};

// ──────────────────────────────────────────────
// QUICK PROMPT CARDS
// ──────────────────────────────────────────────

export interface PromptCard {
  text: string;
  intent: "NELFUND" | "CAC" | "general";
  lang: Language;
}

export const getPromptCards = (lang: Language): PromptCard[] => {
  const s = LANG_STRINGS[lang];
  return [
    { text: s.promptLoan, intent: "NELFUND", lang },
    { text: s.promptCAC, intent: "CAC", lang },
    { text: s.promptHow, intent: "NELFUND", lang },
    { text: s.promptCost, intent: "CAC", lang },
  ];
};

// ──────────────────────────────────────────────
// LANGUAGE DETECTION — keywords per language
// ──────────────────────────────────────────────

export const LANG_KEYWORDS: Record<string, string[]> = {
  pidgin: [
    "how far",
    "i wan",
    "abeg",
    "oya",
    "wetin",
    "na",
    "dem",
    "dey",
    "beta",
    "sabi",
    "no bi",
    "comot",
    "done",
    "chop",
    "guy",
    "my guy",
    "bro",
    "wetin dey",
    "you dey",
    "i don",
    "make i",
    "e be",
    "e dey",
    "for",
    "dere",
    "dis",
    "dat",
  ],
  ha: [
    "sannu",
    "ina",
    "kana",
    "yaya",
    "menene",
    "wane",
    "wannan",
    "don Allah",
    "na gode",
    "to",
    "ba",
    "da",
    "a'a",
    "eh",
    "gaskiya",
    "tabbas",
    "kuma",
    "amma",
    "sai",
    "daga",
    "cikin",
    "kudin",
    "kudi",
    "neman",
    "lamuni",
    "kasuwanci",
  ],
  yo: [
    "bawo",
    "pẹlẹ o",
    "e kaaro",
    "e kaasan",
    "e ku irole",
    "mo fe",
    "mo nilo",
    "jowo",
    "o seun",
    "beeni",
    "rara",
    "nkan",
    "kini",
    "ibi",
    "nibe",
    "ile",
    "ise",
    "owo",
    "ego",
    "awin",
    "ile-ẹkọ",
    "iwe",
    "ako",
    "sise",
    "duro",
    "wa",
    "lo",
    "bo",
  ],
  ig: [
    "kedu",
    "ndewo",
    "daalu",
    "biko",
    "biko nu",
    "ee",
    "mba",
    "gini",
    "ebe",
    "ebe a",
    "ebe ahụ",
    "ụlọ",
    "ọrụ",
    "ego",
    "mbinye",
    "ụlọ akwụkwọ",
    "akwụkwọ",
    "azụmahịa",
    "debanye",
    "aha",
    "bido",
    "mechaa",
    "gaa",
    "bịa",
    "nke ọma",
    "nke",
    "na",
    "ga",
    "m",
    "gị",
    "anyị",
  ],
};

// ──────────────────────────────────────────────
// SCAM DETECTION KEYWORDS
// ──────────────────────────────────────────────

export const SCAM_KEYWORDS = [
  "agent",
  "pay",
  "fee",
  "20k",
  "10k",
  "5k",
  "help me apply",
  "middleman",
  "express fee",
  "processing charge",
  "facilitation fee",
  "connection",
  "inside person",
  "commission",
  "broker",
  "charge",
  "payment",
  "pay someone",
  "pay money",
  "send money",
  "transfer",
  "pay agent",
  "pay for",
  "pay naira",
  "pay somebody",
  "help me process",
  "fast track",
  "fast-track",
  "quick approval",
  "guaranteed",
  "connection fee",
  "settlement",
  "kola",
  "dash",
  "tips",
  "bribe",
  "bribe",
  "speed money",
  "pressing",
  "urgent fee",
];

// ──────────────────────────────────────────────
// CONSTANTS
// ──────────────────────────────────────────────

export const APP_NAME = "Citizen AI";
export const APP_TAGLINE = "Your guide to government services";
export const STORAGE_KEY_THREADS = "citizen_ai_threads";
export const STORAGE_KEY_ACTIVE_THREAD = "citizen_ai_active_thread";
export const STORAGE_KEY_LANG = "citizen_ai_lang";
export const MAX_THREADS = 50;